# Generated by Django 5.1.1 on 2024-09-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=255)),
                ("rating", models.FloatField()),
                ("image", models.CharField(max_length=255)),
            ],
        ),
    ]
